version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    container_name: php-app
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
